site_name: Travel Buddy API

nav:
  - Главная: index.md
  - Описание проекта: description.md
  - База данных: database.md
  - API: api.md
  - Авторизация: auth.md
  - Тестирование: testing.md
  - Заключение: conclusion.md

theme:
  name: material